2022-02-02 20:44:18,215 INFO    MainThread:13515 [wandb_setup.py:_flush():75] Loading settings from /home/yogender/.config/wandb/settings
2022-02-02 20:44:18,215 INFO    MainThread:13515 [wandb_setup.py:_flush():75] Loading settings from /home/yogender/Desktop/KaggleHousePricePrediction/RavirajMlOps/MLOps-Basics/week_2_hydra_config/multirun/2022-02-02/20-44-10/0/wandb/settings
2022-02-02 20:44:18,215 INFO    MainThread:13515 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-02-02 20:44:18,215 WARNING MainThread:13515 [wandb_setup.py:_flush():75] Could not find program at train.py
2022-02-02 20:44:18,216 INFO    MainThread:13515 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': None, 'program': 'train.py'}
2022-02-02 20:44:18,216 INFO    MainThread:13515 [wandb_init.py:_log_setup():386] Logging user logs to /home/yogender/Desktop/KaggleHousePricePrediction/RavirajMlOps/MLOps-Basics/week_2_hydra_config/multirun/2022-02-02/20-44-10/0/wandb/run-20220202_204418-3thou8ol/logs/debug.log
2022-02-02 20:44:18,216 INFO    MainThread:13515 [wandb_init.py:_log_setup():387] Logging internal logs to /home/yogender/Desktop/KaggleHousePricePrediction/RavirajMlOps/MLOps-Basics/week_2_hydra_config/multirun/2022-02-02/20-44-10/0/wandb/run-20220202_204418-3thou8ol/logs/debug-internal.log
2022-02-02 20:44:18,216 INFO    MainThread:13515 [wandb_init.py:init():420] calling init triggers
2022-02-02 20:44:18,216 INFO    MainThread:13515 [wandb_init.py:init():425] wandb.init called with sweep_config: {}
config: {}
2022-02-02 20:44:18,216 INFO    MainThread:13515 [wandb_init.py:init():471] starting backend
2022-02-02 20:44:18,217 INFO    MainThread:13515 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-02 20:44:18,226 INFO    MainThread:13515 [backend.py:ensure_launched():219] starting backend process...
2022-02-02 20:44:18,236 INFO    MainThread:13515 [backend.py:ensure_launched():224] started backend process with pid: 13564
2022-02-02 20:44:18,247 INFO    MainThread:13515 [wandb_init.py:init():480] backend started and connected
2022-02-02 20:44:18,253 INFO    MainThread:13515 [wandb_init.py:init():550] updated telemetry
2022-02-02 20:44:18,276 INFO    MainThread:13515 [wandb_init.py:init():581] communicating current version
2022-02-02 20:44:18,746 INFO    MainThread:13515 [wandb_init.py:init():586] got version response 
2022-02-02 20:44:18,746 INFO    MainThread:13515 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-02-02 20:44:48,747 INFO    MainThread:13515 [interface_shared.py:_communicate_run():313] couldn't get run from backend
2022-02-02 20:44:48,747 ERROR   MainThread:13515 [wandb_init.py:init():601] backend process timed out
2022-02-02 20:44:48,748 ERROR   MainThread:13515 [wandb_init.py:init():610] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-02-02 20:44:48,772 ERROR   MainThread:13515 [wandb_init.py:init():978] error
Traceback (most recent call last):
  File "/home/yogender/miniconda3/envs/MLOps/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 951, in init
    run = wi.init()
  File "/home/yogender/miniconda3/envs/MLOps/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 614, in init
    backend.cleanup()
  File "/home/yogender/miniconda3/envs/MLOps/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 248, in cleanup
    self.interface.join()
  File "/home/yogender/miniconda3/envs/MLOps/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 458, in join
    super().join()
  File "/home/yogender/miniconda3/envs/MLOps/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "/home/yogender/miniconda3/envs/MLOps/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "/home/yogender/miniconda3/envs/MLOps/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/yogender/miniconda3/envs/MLOps/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-02-02 20:44:56,106 INFO    MainThread:13515 [wandb_setup.py:_flush():75] Loading settings from /home/yogender/.config/wandb/settings
2022-02-02 20:44:56,107 INFO    MainThread:13515 [wandb_setup.py:_flush():75] Loading settings from /home/yogender/Desktop/KaggleHousePricePrediction/RavirajMlOps/MLOps-Basics/week_2_hydra_config/multirun/2022-02-02/20-44-10/0/wandb/settings
2022-02-02 20:44:56,107 INFO    MainThread:13515 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-02-02 20:44:56,107 WARNING MainThread:13515 [wandb_setup.py:_flush():75] Could not find program at train.py
2022-02-02 20:44:56,107 INFO    MainThread:13515 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': None, 'program': 'train.py'}
2022-02-02 20:44:56,107 INFO    MainThread:13515 [wandb_init.py:_log_setup():386] Logging user logs to /home/yogender/Desktop/KaggleHousePricePrediction/RavirajMlOps/MLOps-Basics/week_2_hydra_config/multirun/2022-02-02/20-44-10/1/wandb/run-20220202_204456-gi7mlpmj/logs/debug.log
2022-02-02 20:44:56,107 INFO    MainThread:13515 [wandb_init.py:_log_setup():387] Logging internal logs to /home/yogender/Desktop/KaggleHousePricePrediction/RavirajMlOps/MLOps-Basics/week_2_hydra_config/multirun/2022-02-02/20-44-10/1/wandb/run-20220202_204456-gi7mlpmj/logs/debug-internal.log
2022-02-02 20:44:56,108 INFO    MainThread:13515 [wandb_init.py:init():420] calling init triggers
2022-02-02 20:44:56,108 INFO    MainThread:13515 [wandb_init.py:init():425] wandb.init called with sweep_config: {}
config: {}
2022-02-02 20:44:56,108 INFO    MainThread:13515 [wandb_init.py:init():471] starting backend
2022-02-02 20:44:56,108 INFO    MainThread:13515 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-02 20:44:56,110 INFO    MainThread:13515 [backend.py:ensure_launched():219] starting backend process...
2022-02-02 20:44:56,114 INFO    MainThread:13515 [backend.py:ensure_launched():224] started backend process with pid: 13650
2022-02-02 20:44:56,115 INFO    MainThread:13515 [wandb_init.py:init():480] backend started and connected
2022-02-02 20:44:56,120 INFO    MainThread:13515 [wandb_init.py:init():550] updated telemetry
2022-02-02 20:44:56,136 INFO    MainThread:13515 [wandb_init.py:init():581] communicating current version
2022-02-02 20:44:56,707 INFO    MainThread:13515 [wandb_init.py:init():586] got version response 
2022-02-02 20:44:56,707 INFO    MainThread:13515 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-02-02 20:45:26,708 INFO    MainThread:13515 [interface_shared.py:_communicate_run():313] couldn't get run from backend
2022-02-02 20:45:26,708 ERROR   MainThread:13515 [wandb_init.py:init():601] backend process timed out
2022-02-02 20:45:26,709 ERROR   MainThread:13515 [wandb_init.py:init():610] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-02-02 20:45:26,727 ERROR   MainThread:13515 [wandb_init.py:init():978] error
Traceback (most recent call last):
  File "/home/yogender/miniconda3/envs/MLOps/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 951, in init
    run = wi.init()
  File "/home/yogender/miniconda3/envs/MLOps/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 614, in init
    backend.cleanup()
  File "/home/yogender/miniconda3/envs/MLOps/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 248, in cleanup
    self.interface.join()
  File "/home/yogender/miniconda3/envs/MLOps/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 458, in join
    super().join()
  File "/home/yogender/miniconda3/envs/MLOps/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "/home/yogender/miniconda3/envs/MLOps/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "/home/yogender/miniconda3/envs/MLOps/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/yogender/miniconda3/envs/MLOps/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
